from fastapi import APIRouter
from pydantic import BaseModel

router = APIRouter()


class GenerateRequest(BaseModel):
    document_type: str
    parties: str
    terms: str
    effective_date: str


@router.get("/")
def home():
    return {"message": "LegalEase AI backend is running"}


@router.post("/generate")
def generate_document(data: GenerateRequest):

    document = f"""
{data.document_type}

Effective Date: {data.effective_date}

PARTIES

{data.parties}

TERMS AND CONDITIONS

{data.terms}

AGREEMENT

The parties agree to the terms and conditions stated above.
This document is generated by LegalEase AI and should be
reviewed for accuracy and applicable jurisdiction before use.
"""

    return {
        "document": document.strip(),
        "model": "LegalEase Mock AI",
        "mock": True
    }